default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.69
    hooks:
      - id: ty
        stages: [pre-push]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest --cov
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: coverage
        name: coverage
        entry: uv run coverage report --fail-under=90
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
